name: .NET Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    name: Cross-Compile and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Package
        run: |
          tag=$(git describe --tags --abbrev=0)
          declare -a targets=("osx-arm64" "osx-x64" "win-x64" "linux-x64")

          for target in "${targets[@]}"
          do
            release_name="Chirp.CLI-$tag-$target"
            dotnet publish src/Chirp.CLI/Chirp.CLI.csproj -c Release --framework net7.0 --runtime $target -o "$release_name"

            # Create a zip archive
            7z a -tzip "${release_name}.zip" "./${release_name}/*"

            # Optionally, create a tar.gz archive (uncomment if needed)
            # tar -czvf "${release_name}.tar.gz" "./${release_name}/" 

            rm -r "$release_name"
          done

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Chirp.CLI-*.zip
            # Add Chirp.CLI-*.tar.gz if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
