name: .NET Build and Test

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "test/**"
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - "test/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test integration tests
        run: dotnet test --filter Category=Integration --no-build --verbosity normal
      - name: Test unit tests
        run: dotnet test --filter Category=Unit --no-build --verbosity normal
