name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ["linux", "windows", "macOS"]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build and Package
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-${{ matrix.target }}"
          output_dir="$HOME/$release_name"
          # Build everything
          dotnet publish src/Chirp.CLI.Client/Chirp.CLI.csproj --framework net7.0 --runtime "${{ matrix.target }}" -c Release -o "$output_dir"
          # Create a ZIP file for each platform
          cd "$HOME"
          zip -r "$release_name.zip" "$release_name"
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: chirp-artifact-${{ matrix.target }}
          path: $HOME/Chirp-*.zip

      - name: Publish Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.upload-release-artifact.outputs.artifact_paths }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
